### PR TITLE
fix: improve button hover and focus colors

### LINKED ISSUE #3450: [Bug]: Red danger buttons should have visible text on hover
### What happened?

When red danger buttons are hovered right now, the text is not visible:

Image
Image
Image
Image
Image
Image
Image

Also, when they are focused, there is currently no focus border

### How can we reproduce the bug?

- hover over any danger button

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### PR DESCRIPTION
**Pull request by aldenquimby**
# Description

Fixes #3450 

When danger buttons are hovered, the text is now visible:
Image
Image
Image
Image
Image

The focus indicator also works now:
hover-danger

And the focus change applied to all solid (non-outlined) buttons. Focus was previously invisible and is now shown:
hover

---

## Implementation note, gotchas, related work and Future TODOs (optional)

-

### Pre-launch Checklist
- [x] The [Documentation] is updated accordingly, or this PR doesn't require it.
- [x] I updated/added relevant documentation.
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making, or this PR is test-exempt.
- [x] All existing and new tests are passing.

### Merging:
- Squash merge to dev
- Merge commit to publish-alpha and main

[Documentation]: https://www.100ms.live/docs

### CODE REVIEW

File: packages/roomkit-react/src/Button/Button.tsx [hunk 1]
```diff
@@ -70,7 +74,7 @@ const getButtonVariants = (
       border: `1px solid ${active}`,
     },
     '&:not([disabled]):focus-visible': {
-      boxShadow: `0 0 0 3px ${base}`,
+      boxShadow: `0 0 0 3px $colors${hover}`,
```
Comment (aldenquimby) [inline packages/roomkit-react/src/Button/Button.tsx:77]: 1. `${base}` was rendering an invalid CSS var here. Add `$colors` fixed that
2. `${base}` is the background color, so it was blending in. using `${hover}` instead is clearer

**Review by raviteja83 — APPROVED** [review]
